# Generated by Django 3.1.7 on 2021-03-30 21:18

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'get_latest_by': 'modified'},
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='weight',
        ),
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default='asfd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
